/* Lógico_1: */

CREATE TABLE PESQUISADOR (
    ID_PS VARCHAR PRIMARY KEY UNIQUE,
    NOME_PS VARCHAR,
    LATTES_PS VARCHAR,
    DATA_ENT_PS DATE,
    CLASS_PS VARCHAR,
    IMG_PS BLOB
);

CREATE TABLE ESPECIE (
    ID_SPECIE INTEGER PRIMARY KEY UNIQUE,
    NOME_SPECIE VARCHAR,
    REINO_SPECIE VARCHAR,
    FILO_SPECIE VARCHAR,
    CLASSE_SPECIE VARCHAR,
    ORDEM_SPECIE VARCHAR,
    FAMILIA_SPECIE VARCHAR,
    GENERO_SPECIE VARCHAR,
    IMG_SPECIE BLOB
);